name: Linters and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  linter-and-test:
    uses: modyo-connect/workflows/.github/workflows/widgets-lint-and-test.yml@main
    with:
      legacy-peer-deps: true