name: Deploy Gh Pages

on:
  push:
    branches:
      - feat/vite-commons
jobs:
    deploy-to-gh-pages:
      uses: modyo-connect/workflows/.github/workflows/widgets-deploy-github-page.yml@main
      with:
        legacy-peer-deps: true